# Generated by Django 5.2 on 2025-04-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jd_sports_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jersey',
            name='image_url',
        ),
        migrations.AddField(
            model_name='jersey',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='jersey_images/'),
        ),
        migrations.AlterField(
            model_name='jersey',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='jersey',
            name='size',
            field=models.CharField(max_length=10),
        ),
    ]
